openapi: 3.0.0
info:  
  title: Census API
  version: "1.0"
  description: Allows searching various statistics in the United States by region, state, county, city, and zipcode.
paths:
  /regions:
    get:
      summary: Returns the official regions in the United States
      responses:
        200:
          description: successful operation
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties: 
                    code: 
                      type: integer
                    name:
                      type: string